# Generated by Django 4.1.7 on 2023-04-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_articulocarrito_envio_usuario_delete_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulocarrito',
            name='ingresado_el',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='fecha_ingreso',
        ),
    ]
