# Generated by Django 4.1.7 on 2023-04-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_remove_articulocarrito_ingresado_el_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticuloCarrito',
            new_name='Articulo',
        ),
    ]
