# Generated by Django 4.1.7 on 2023-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_articulocarrito_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='estado',
        ),
        migrations.AddField(
            model_name='articulo',
            name='cantidad',
            field=models.TextField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.TextField(default='samsung', max_length=100),
        ),
    ]
