# Generated by Django 4.1.7 on 2023-04-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_remove_articulo_estado_articulo_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='estado_de_envio',
        ),
        migrations.AddField(
            model_name='envio',
            name='ciudad',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='cp',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='envio',
            name='provincia',
            field=models.TextField(default=' ', max_length=100),
        ),
    ]
